//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COMP2007_FinalAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table
    {
        public int projectID { get; set; }
        public string projectName { get; set; }
        public string date { get; set; }
        public Nullable<int> HoursWorked { get; set; }
        public string typeOfWork { get; set; }
        public string description { get; set; }
    }
}
